# Generated by Django 4.0.1 on 2022-01-22 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('favs', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('cest', models.CharField(max_length=4000)),
            ],
        ),
    ]
