# Generated by Django 4.0.1 on 2022-01-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_features_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
