# Generated by Django 4.0.1 on 2022-01-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_features_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
